// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "This is not Web app", Scope = "member", Target = "~M:Shawt.Controllers.LinksController.GetAsync(System.Int32,System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.IList{Shawt.Models.LinkDto}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "This is not Web app", Scope = "member", Target = "~M:Shawt.Controllers.LinksController.GetDetailsAsync(System.Guid)~System.Threading.Tasks.Task{Shawt.Models.LinkWithLogsDto}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "This is not Web app", Scope = "member", Target = "~M:Shawt.Controllers.MetadataController.Get~System.Threading.Tasks.Task{Shawt.Models.OpenIdClientSettings}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Application is intended for a limited local audience and will therefore not be localized", Scope = "member", Target = "~M:Shawt.Controllers.RedirectController.Get(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Application is intended for a limited local audience and will therefore not be localized", Scope = "member", Target = "~M:Shawt.Controllers.RedirectController.Get(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Application is intended for a limited local audience and will therefore not be localized", Scope = "member", Target = "~M:Shawt.Controllers.LinksController.Post(Shawt.Models.LongUrl)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Shawt.Controllers.LinksController.GetDetailsAsync(System.Guid)~System.Threading.Tasks.Task{Shawt.Models.LinkWithLogsDto}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Shawt.Controllers.LinksController.GetAsync(System.Int32,System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.IList{Shawt.Models.LinkDto}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Shawt.Controllers.RedirectController.Get(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
