// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shawt.Data;

public partial class ApplicationUsers
{
    public Guid ApplicationId { get; set; }

    public string UserName { get; set; }
}