// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shawt.Data;

public partial class Link
{
    public int Id { get; set; }

    public Guid LinkId { get; set; }

    public string OriginalLink { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? Clicks { get; set; }

    public virtual ICollection<Log> Log { get; set; } = new List<Log>();
}