// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shawt.Data;

public partial class RateLimitRules
{
    public int Id { get; set; }

    public string ClientId { get; set; }

    public string Endpoint { get; set; }

    public string Period { get; set; }

    public int RequestLimit { get; set; }
}