// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shawt.Data;

public partial class RateLimitCounters
{
    public string Id { get; set; }

    public DateTime Timestamp { get; set; }

    public double Count { get; set; }
}